"""Build the GitHub Pages site (docs/) from the writeup and results.

    uv run python scripts/build_docs.py

* ``docs/index.md``  – landing page (from README, links rewritten)
* ``docs/writeup.md`` – the writeup with repo-relative links turned into GitHub URLs
* ``docs/tables_cpu.md`` – rendered result tables
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

REPO = "https://github.com/xiyiji/cs336-assignment2-systems"
ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"


def rewrite_links(md: str, base: str) -> str:
    """Turn relative repo links into GitHub blob/tree URLs; keep in-site links."""

    def repl(m):
        text, target = m.group(1), m.group(2)
        if target.startswith(("http://", "https://", "#", "mailto:")):
            return m.group(0)
        clean = target
        while clean.startswith("./"):
            clean = clean[2:]
        while clean.startswith("../"):
            clean = clean[3:]
        if clean in ("writeup/writeup.md", "writeup.md"):
            return f"[{text}](writeup.html)"
        if clean.endswith("tables_cpu.md"):
            return f"[{text}](tables_cpu.html)"
        kind = "tree" if clean.endswith("/") or "." not in clean.rsplit("/", 1)[-1] else "blob"
        return f"[{text}]({REPO}/{kind}/main/{clean})"

    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", repl, md)


def main() -> None:
    DOCS.mkdir(exist_ok=True)
    (DOCS / "_config.yml").write_text(
        "title: CS336 Assignment 2 — Systems\n"
        "description: FlashAttention-2 (PyTorch + Triton), DDP, optimizer sharding, FSDP, profiling — implemented from scratch\n"
        "theme: jekyll-theme-cayman\n"
        "show_downloads: false\n"
        f"github:\n  repository_url: {REPO}\n"
    )
    readme = (ROOT / "README.md").read_text()
    (DOCS / "index.md").write_text(rewrite_links(readme, REPO))
    writeup = (ROOT / "writeup" / "writeup.md").read_text()
    (DOCS / "writeup.md").write_text("---\ntitle: Writeup\n---\n\n" + rewrite_links(writeup, REPO))
    tables = subprocess.run(
        ["uv", "run", "python", "scripts/make_tables.py", "results/cpu"], cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout
    (ROOT / "writeup" / "tables_cpu.md").write_text("# CPU results (auto-generated by scripts/make_tables.py)\n\n" + tables)
    (DOCS / "tables_cpu.md").write_text("---\ntitle: CPU result tables\n---\n\n" + tables)
    print("docs/ written:", sorted(p.name for p in DOCS.iterdir()))


if __name__ == "__main__":
    main()
